### PR TITLE
Assignment 5 - Redo Pull Request (headSimulatorTwo)

### PR DESCRIPTION
**Pull request by davidh167**
We have: 

* Updated the Blackboard
* Moved some of the used classes into the library (we created our subdirectory within the library module, per your recommendation)
* Removed Websockets
* Cleaned up comments
* Refactored other files

### CODE REVIEW

**Review by javiergs — CHANGES_REQUESTED** [review]
Do not modify files in Modules that are not yours or shared
i.e., only include in your pull request your Module and Library Module.

**Review by javiergs — CHANGES_REQUESTED** [review]
- Remove your folder .idea from the commit
- Remove all class files (compiled files) from the commit
- For the files in the Library module put them in a package to avoid affecting the ones submitted by others. I will review an create a common Library later.

**Comment by javiergs** [comment]
- Do not commit the target folder (class files).
- Maybe the README.md that you are uploading should be inside your Module otherwise explain the update

**Review by javiergs — CHANGES_REQUESTED** [review]
- Do not commit the target folder (class files).
- Maybe the README.md that you are uploading should be inside your Module otherwise explain the update

**Comment by davidh167** [comment]
> * Do not commit the target folder (class files).
> * Maybe the README.md that you are uploading should be inside your Module otherwise explain the update

As of the latest commits, there is no 'target' folder (they've been deleted)
The README changes were accidentally applied when using IntelliJ's refactoring tool. The names of some classes changed in the README file, which has since been reset.

**Comment by javiergs** [comment]
Double check. I still see them. I just deleted the README.md from your submission and a *.lck.
But there are several others that should not be there.

**Review by javiergs — CHANGES_REQUESTED** [review]
Double check. I still see them. I just deleted the README.md from your submission and a *.lck. But there are several others that should not be there.

**Review by javiergs — APPROVED** [review]
Clossing the request. Trying to add as many files as possible. 
Note: - target files, idea folder, etc should not be included.

**Pull request merged**
